FROM alpine:3.21 AS download

ARG RESTIC_VERSION=0.15.1
ARG RESTIC_DOWNLOAD_BASE=https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/
ARG RESTIC_DOWNLOAD=${RESTIC_DOWNLOAD_BASE}/restic_${RESTIC_VERSION}_linux_amd64.bz2
ARG RESTIC_HASHES=${RESTIC_DOWNLOAD_BASE}/SHA256SUMS
ARG RESTIC_HASHES_SIG=${RESTIC_DOWNLOAD_BASE}/SHA256SUMS.asc

RUN apk add --no-cache gpgv gpg gnupg-keyboxd dirmngr gpg-agent curl coreutils && \
  curl -L --remote-name-all ${RESTIC_DOWNLOAD} ${RESTIC_HASHES} ${RESTIC_HASHES_SIG} && \
  gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys  CF8F18F2844575973F79D4E191A6868BD3F7A907 && \
  gpg --verify SHA256SUMS.asc && \
  sha256sum -c --ignore-missing SHA256SUMS && \
  bunzip2 restic_${RESTIC_VERSION}_linux_amd64.bz2 && \
  chmod +x restic_${RESTIC_VERSION}_linux_amd64 && \
  mv restic_${RESTIC_VERSION}_linux_amd64 /usr/local/bin/restic

FROM alpine:3.21

RUN apk --no-cache upgrade

RUN apk --no-cache add ca-certificates bash

COPY --from=download /usr/local/bin/restic /usr/local/bin/
COPY docker/backup/backup.sh docker/backup/restore-backup.sh /usr/local/bin/
